Description du modèle de recommendation
AdrKacz/super-duper-guacamole pull request #12
Opened 2022-01-13 17:54 UTC by mbeaufre

2022-01-20 08:02 UTC, AdrKacz requested changes
Quelques point à revoir, le plus important reste la simplification des phrases et la grammaire pour l'instant 😇 J'ai mis beaucoup de *comment*, mais ça devrait vite être réglé, t'as déjà fait le gros du travail 👌

2022-01-20 08:02 UTC, AdrKacz commented on model/model-descrip.md
> +## Uses of a Meta-Model
Essaie d'expliquer ce que tu entends par *meta-model* et comment tu comptes t'en servir, la *bullet list* n'est pas super clair et elle combine des *items* par vraiment reliés

2022-01-20 09:20 UTC, mbeaufre commented on model/model-descrip.md
> +**Version 0**
Done. OK

2022-01-20 09:21 UTC, mbeaufre commented on model/model-descrip.md
> +One of the main idea of the project is to develop a software solution to assign people **apparently randomly** to conversation groups. However, we aim to create groups which have a positive dynamic,
OK. Clear.

2022-01-20 09:24 UTC, mbeaufre commented on model/model-descrip.md
> +- The message that were exchange in the different conversations he was involved in.
Clair

2022-01-20 09:24 UTC, mbeaufre commented on model/model-descrip.md
> +- The ID of the people he has talked with
Effectivement c'était pas clair. Je voulais dire qu'il avait pas accès à l'information 'ID *i* a parlé à ID *j* si il n'est ni *i*, ni *j*. Je corrige.

2022-01-20 09:33 UTC, mbeaufre commented on model/model-descrip.md
> +With the local information available (detailled later), we compute scores/weights, of n dim, **in the vision of each ID/individual**. This reprensentation is **PRIVATE**.
Pas forcément, tu peux trouver d'autres manières de computer un score. Et pour trouver une certaine distance (ou classement) par la suite tu as bien besoin d'une valeur (qu'on peut appeler score ou poids).

2022-01-20 09:42 UTC, mbeaufre commented on model/model-descrip.md
> +With the local information available (detailled later), we compute scores/weights, of n dim, **in the vision of each ID/individual**. This reprensentation is **PRIVATE**.
Ok. J'essaie de clarifier

2022-01-20 09:54 UTC, mbeaufre commented on model/model-descrip.md
> +e.g : See below, reprensentation in 2D (let's say it is a PCAof the generated weights)
NON

2022-01-20 10:34 UTC, mbeaufre commented on model/model-descrip.md
> +- e<sub>2</sub> knows e<sub>j</sub> for j∈[m+1,2m] because he is involved in an other conversation.\
Effectivement

2022-01-20 10:35 UTC, mbeaufre commented on model/model-descrip.md
> +e.g : See below, reprensentation in 2D (let's say it is a PCAof the generated weights)
C'est fait

2022-01-20 10:35 UTC, mbeaufre commented on model/model-descrip.md
> +In the vision of e<sub>1</sub>, he is closer to e<sub>3</sub>  than to e<sub>2</sub> , but in the vision of e<sub>3</sub>, e<sub>2</sub> is closer than e<sub>1</sub>. This vision is -or at least can
C'est le score/vecteur de poids. Je vais le préciser.

2022-01-20 10:46 UTC, mbeaufre commented on model/model-descrip.md
> +![img.png](images/reco-2d.png)
OK, supprimé

2022-01-20 10:57 UTC, mbeaufre commented on model/model-descrip.md
> +- Discrete weighting : Giving the rank of the e<sub>i</sub> in the 'Proximity ranking', we attribute fixed weights. Could be appropriate if we don't have a distance to compute. (Example: In the begin
OK

2022-01-20 11:03 UTC, mbeaufre commented on model/model-descrip.md
> +- Distance (continuous) weighting : Compute d(e<sub>1</sub>, e<sub>i</sub>), where d is an distance to define. Then the weithing term is
Effectivement oups

2022-01-20 11:40 UTC, mbeaufre commented on model/model-descrip.md
> +- Content of the messages --> Sentiment analysis : Pay attention to the ironie/insults that can skew the results
En cours

2022-01-20 11:47 UTC, mbeaufre commented on model/model-descrip.md
> +## Uses of a Meta-Model
:)

2022-01-20 11:47 UTC, mbeaufre commented on model/model-descrip.md
> +### Test : Use GPT-2 to see if it is working correctly.
JE C PAS ANCHOR

2022-02-17 12:11 UTC, AdrKacz commented
<img width="714" alt="Screenshot 2022-02-17 at 13 07 00" src="https://user-images.githubusercontent.com/61620013/154478719-6dd8cf95-39ca-4b8a-a9d1-cb1ecf663603.png">

Vire juste les rouges, on verra plus tard pour les jaunes

2022-02-17 12:13 UTC, AdrKacz commented on model/model-descrip.md
> +- Content of the messages --> Sentiment analysis : Pay attention to the ironie/insults that can skew the results
Rajoute une issue puis resolve

2022-02-17 12:13 UTC, AdrKacz commented on model/model-descrip.md
> +### Test : Use GPT-2 to see if it is working correctly.
Pareil, rajoute une issue et resolve

2022-02-17 12:14 UTC, AdrKacz requested changes
Un *have not* puis c'est plié, rajoute des Issue pour les points commentaires non traité (sur les source)

2022-02-17 12:53 UTC, AdrKacz approved these changes
Parfait

2022-02-22 16:37 UTC, merged