Update aws sdk
AdrKacz/super-duper-guacamole pull request #82
Opened 2022-04-22 15:13 UTC by AdrKacz

# Update AWS SDK

1. Update AWS SDK to v3
2. Decompose the logic in multiple *Lambda* (no helpers dependencies) --> **modular**
3. Add *Load Test* (cannot wait for a message for now, will be added soon, not on me, **I've create a _legacy-main_ branch to do the benchmark later**
4. Dedicated *Lambda* for message and notification

# Left to do
1. Target each user individually for *notification*
2. Create a *notification* for *prod* and for *dev* (**load test send thousands of notifications**)

2022-04-22 16:16 UTC, AdrKacz commented
⚠️⚠️⚠️ **Ne merge pas la PR** ⚠️⚠️⚠️

J'ai trouvé un moyen de contourner le problème de *Artillery*, je vais mettre à jour le *load test*

2022-04-22 19:45 UTC, AdrKacz commented
Après vérification, le nouveau code est **CINQ FOIS** plus long que le précédent pour l'envoie de message ...
Je vais voir comment je peux améliorer ça. C'est nul là 🤔

2022-04-23 10:50 UTC, AdrKacz commented
Le comparatif des deux versions est disponible dans `artillery/results/html`.

Pour voir la version web (interactive, donc c'est fun 🎉)

- [La version dev](https://raw.githack.com/AdrKacz/super-duper-guacamole/update-aws-sdk/artillery/results/html/results-dev.html) (c'est celle que tu *review*)
- [La version prod](https://raw.githack.com/AdrKacz/super-duper-guacamole/update-aws-sdk/artillery/results/html/results-prod.html) (c'est l'ancienne version, actuellement en prod)

2022-04-24 08:21 UTC, mbeaufre commented on artillery/README.md
> +However, in a real world solution, we will receive message that we are not wainting for.
*waiting

2022-04-24 08:35 UTC, mbeaufre requested changes
assets/terrastruct/groups.gif, NOOOO. If I was epileptic I would be already dead. Eyes killer.

2022-04-24 08:38 UTC, mbeaufre approved these changes

2022-04-24 09:59 UTC, merged